

CREATE SEQUENCE SEQ_USERS INCREMENT BY 1 START WITH 10000;
CREATE SEQUENCE SEQ_MESSAGE INCREMENT BY 1 START WITH 1;

CREATE TABLE USERS(ID NUMBER(7) CONSTRAINT USER_ID_PK PRIMARY KEY,
USERNAME VARCHAR2(20) CONSTRAINT USER_USERNAME_UK UNIQUE,
PASSWORD VARCHAR2(20) NOT NULL,
EMAIL VARCHAR2(50) NOT NULL
);

CREATE TABLE MESSAGES(ID NUMBER(7) CONSTRAINT MESSAGE_ID_PK PRIMARY KEY,
SENDID NUMBER(7) NOT NULL,
TITLE VARCHAR2(40) NOT NULL,MSGCONTENT VARCHAR2(400) NOT NULL,
STATE NUMBER(1) NOT NULL,
RECEIVEID NUMBER(7) NOT NULL,
MSG_CREATE_DATE VARCHAR2(20) NOT NULL,
CONSTRAINT FK_S_NAME FOREIGN KEY(SENDID) REFERENCES USERS(ID),
CONSTRAINT FK_R_NAME FOREIGN KEY(RECEIVEID)REFERENCES USERS(ID)
);

insert into USERS values(SEQ_USERS.nextval,'zhangsan','123456','123@qq.com')